services:
  app:
    image: node:22-alpine
    container_name: app
    working_dir: /app
    restart: always
    command: [ "sh", "-c", "npm install && npm start" ]
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
